version: '3.9'

services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=bankApi
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bankApi